---
name: Desafio de Data Science
locale: pt
type: learning
beta: false
teacher_info: ''
language: python3
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 12
- 13
- 6
- 7
- 8
- 9
- 10
- 11
- 14
- 5
- 15
- 16
- 17
- 18
- 22
- 24
- 25
- 20
- 21
- 23
- 19
- 26
private: false
