---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 20, 54, 140
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 21, 55, 144
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 21, 57, 150
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 21, 55, 150
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 20, 54, 140
  checked: false
name: 'Lógica: Sequencia de Fibonacci'
