---
locale: pt
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: a
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: f
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: d
  checked: false
name: Teste
