---
locale: pt
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '8'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '15'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '18'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '20'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '28'
  checked: false
name: 'Aritmética: Notebooks com defeito'
