---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '2'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '3'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '5'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '8'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '9'
  checked: false
name: 'Lógica: encontre o número faltante'
