---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '8'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '21'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '48'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '56'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '63'
  checked: false
name: 'Lógica: encontre o número faltante 2'
