---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: k + 5
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: k + 10
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 2k + 10
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 3k + 15
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 2k + 25
  checked: false
name: Novo exercício
