---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 1; 9
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "-1; 13"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "-2; 15"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "-4; 19"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "-5; 21"
  checked: true
name: 'Lógica: Encontre o valor dos mármores'
