---
locale: pt
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 300, 320, 260
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 320, 320, 256
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 300, 300, 256
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 320, 320, 260
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 320, 340, 260
  checked: false
name: 'Lógica: Sequencia com padrões'
